# -*- coding: utf-8 -*-
"""Aula15/02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fgl3aOiN0Gdv2-oC4o0z36LiCr7GI4uJ

# **Aula 5 - Laços de repetição 2**

## Atividade 1

1. Faça um programa que leia 5 números e informe o maior número.
"""

maior_numero = float('-inf')

for banana in range(5):
  numero = float(input(f'Digite o {banana+1}° número: '))
  if numero > maior_numero:
    maior_numero = numero

  print(f'O maior número digitado é {maior_numero}')

"""## Atividade 2

2. Faça um programa que verifique e mostre os números entre 1.000 e 2.000
(inclusive) que, quando divididos por 11 produzam resto igual a 2.
"""

for numero in range(1000,2001):
  if numero%11 == 2:
    print(numero)

"""## Atividade 3

3. Faça um programa que leia 5 números e informe a soma e a média dos
números.
"""

soma = 0

for i in range(1,6):
    numero = float(input(f'Digite o {i}° número: '))
    soma += numero
    if i == 5:
      media = soma / i
      print(f'A soma é {soma} e sua média é {media}.')

"""## Atividade 4

4. Faça um programa que receba um número e usando laços de repetição
calcule e mostre a tabuada desse número.
"""

numero = int(input('Digite um número que ce nao sabe a tabuada: '))

print(f'Tabuada do número {numero}:')
for i in range(1,11):
  print(f'{numero} x {i} = {numero*i}')

"""## Atividade 5

5. Faça um programa que mostre as tabuadas dos números de 1 a 10 usando
laços de repetição.
"""

for a in range(1,11):
  print(f'Tabuada do número: {a}')
  for b in range(1,11):
    print(f'{a} x {b} = {a*b}')

"""## Atividade 6

6. Faça um programa que imprima na tela os números de 1 a 20, um abaixo
do outro. Depois modifique o programa para que ele mostre os números
um ao lado do outro.
"""

for i in range(1,21):
  print(i)

print(list(range(1,21)))

"""## Atividade 7

7. Faça um programa que imprima na tela apenas os números ímpares entre
1 e 50.
"""

for i in range(1,51):
  if i%2 != 0:
    print(i)

"""## Atividade 8

8. Faça um programa que receba dois números inteiros e gere os números
inteiros que estão no intervalo compreendido por eles.
"""

n1 = int(input('Digite o 1° número: '))
n2 = int(input('Digite o 2° número: '))

if n1 < n2:
  for i in range(n1 + 1,n2):
    print(i)

for i in range(n2 + 1,n1):
  print(i)

"""## Atividade 9

9. Uma loja deseja cadastrar 5 clientes e verificar se o faturamento da loja foi
superior a loja B (faturamento = 54000). Se o faturamento atingir esse valor
mostre na tela uma mensagem contendo em quanto foi superado o
faturamento.
"""

faturamento_lojaA = 0
faturamento_lojaB = 54000
resultado = 'O faturamento da loja A não ultrapassou a loja B.'

for i in range(1,6):
  valor = float(input('Digite valores da loja A: '))
  faturamento_lojaA += valor

if faturamento_lojaA > faturamento_lojaB:
  diferenca = faturamento_lojaA - faturamento_lojaB
  resultado = f'O faturamento da loja A ultrapassou a loja B em R$ {diferenca}.'
elif faturamento_lojaA < faturamento_lojaB:
  resultado = 'O faturamento da loja A não ultrapassou ao da loja B.'
else:
  resultado = f'O faturamento da loja A é o mesmo que o da loja B.'

print(resultado)

"""## Atividade 10

10. Faça um programa que peça 10 números inteiros, calcule e mostre a
quantidade de números pares e a quantidade de números impares.
"""

cont_par = 0
cont_impar = 0

for i in range(10):
  numero = int(input('Digite números: '))
  if numero%2 == 0:
    cont_par += 1
  else:
    cont_impar += 1

print(f'Quantidade de números pares {cont_par}\nQuantidade de números impares: {cont_impar}')

"""## Atividade 11

11. Um funcionário de uma empresa recebe aumento salarial anualmente:
Sabe-se que:

- Esse funcionário foi contratado em 1995, com salário inicial de R$ 1.000,00;
- Em 1996 recebeu aumento de 1,5% sobre seu salário inicial;

A partir de 1997 (inclusive), os aumentos salariais sempre correspondem ao
dobro do percentual do ano anterior. Faça um programa que determine o
salário atual desse funcionário. Após concluir isto, altere o programa
permitindo que o usuário digite o salário inicial do funcionário.
"""

salario = float(input('Digite seu salário base em 1995: R$ '))
percentual = 0.015

for i in range(1996, 2025):
  aumento = salario * percentual
  salario += aumento
  percentual *= 2
  print(f'Salário em {i}: R$ {salario: .2f}')

"""## Atividade 12

12. Faça um programa que peça uma nota, entre zero e dez. Mostre uma
mensagem caso o valor seja inválido e continue pedindo até que o usuário
informe um valor válido.
"""

for i in range(999):
  nota = float(input('Digite uma nota entre 0 e 10: '))
  if nota > 0 and nota < 10:
    break
  else:
    print('Valor Inválido.\n')

"""## Atividade 13

13. Uma loja tem tem uma política de descontos de acordo com o valor da
compra do cliente. Os descontos começam acima dos R$500. A cada 100
reais acima dos R$500,00 o cliente ganha 1% de desconto cumulativo até
25%.
- Por exemplo: R$500 = 1% || R$600,00 = 2% … etc…

Faça um programa que exiba essa tabela de descontos no seguinte formato:

 -Valordacompra – porcentagem de desconto – valor final
"""

compra = float(input('Digite o valor da compra: R$ '))
percentual = 1 if compra >= 500 else 0
valor_compra = compra

for i in range(999):
  valor_compra -= 100
  if valor_compra < 500:
    break
  if percentual == 25:
    break
  percentual += 1

desconto = (compra * percentual) / 100
valor_final = compra - desconto

print(f'Valor da compra: R$ {compra} - Porcentagem de desconto: {percentual}% - Valor final: {valor_final}')

"""## Atividade 14

14. Faça um programa que receba a idade de 15 pessoas e que calcule e
mostre:

a) A quantidade de pessoas em cada faixa etária;

b) A percentagem de pessoas na primeira e na última faixa etária, com relação
ao total de pessoas:

- Até 15 anos
- De 16 a 30 anos
- De 31 a 45 anos
- De 46 a 60 anos
- Acima de 61 anos
"""

qnt_faixa1 = 0
qnt_faixa2 = 0
qnt_faixa3 = 0
qnt_faixa4 = 0
qnt_faixa5 = 0

print('Calculadora de faixa etária:\n')
for i in range(1,16):
  while True:
    idade = int(input(f'Digite a idade {i}: '))
    if idade >= 0:
      break
    print('Idade inválida. Digite novamente.')

  if idade <= 15:
    qnt_faixa1 += 1
  elif idade > 15 and idade <= 30:
    qnt_faixa2 += 1
  elif idade > 30 and idade <= 45:
    qnt_faixa3 += 1
  elif idade > 45 and idade <= 60:
    qnt_faixa4 += 1
  else:
    qnt_faixa5 += 1

  if i == 15:
    percentual_faixa1 = (qnt_faixa1 / i) * 100
    percentual_faixa5 = (qnt_faixa5 / i) * 100

    print(f'Resultados:\nAté 15 anos: {qnt_faixa1}\nDe 16 a 30 anos: {qnt_faixa2}\nDe 31 a 45 anos: {qnt_faixa3}\nDe 46 a 60 anos: {qnt_faixa4}\nAcima de 61 anos: {qnt_faixa5}\n')
    print(f'Percentagem da primeira faixa: {percentual_faixa1: .2f}%\nPercentagem da última faixa: {percentual_faixa5: .2f}%')

"""## Atividade 15

15. Faça um programa que peça dois números, base e expoente, calcule e
mostre o primeiro número elevado ao segundo número. Não utilize a
função de potência da linguagem.
"""

# Utilizando o FOR (funciona apenas com expoentes de numeros interios)
base = float(input('Digite a base para realizar sua potência: '))
expoente = int(input('Digite o expoente da base: '))
potencia = 1

for i in range(1,expoente+1):
  potencia *= base

print(potencia)

# Sem o FOR
base = float(input('Digite a base para realizar sua potência: '))
expoente = float(input('Digite o expoente da base: '))

potencia = base ** expoente

print(potencia)

"""## Atividade 16

16. Faça um programa que mostre todos os primos entre 1 e N sendo N um
número inteiro fornecido pelo usuário. O programa deverá mostrar também
o número de divisões que ele executou para encontrar os números primos.
Serão avaliados o funcionamento, o estilo e o número de testes (divisões)
executados.
"""

qnt_divisoes = 0
num = int(input('Digite um número inteiro: '))

print(f'Números primos entre 1 e {num}:')
for num_teste in range(1,num):
  contador_impar = 3
  if num_teste == 1:
    continue
  if num_teste == 2:
    qnt_divisoes += 1
    print(num_teste)
    continue

  while contador_impar <= num_teste:
    if num_teste%contador_impar == 0:
      qnt_divisoes += 1
      break
    qnt_divisoes += 1
    contador_impar += 2

  if num_teste == contador_impar:
    print(num_teste)

print(f'Quantidade de divisões necessárias para encontra-los: {qnt_divisoes}')