# -*- coding: utf-8 -*-
"""Aula09/02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bhut5TLySayu-L5Ls1ivkYftsErRtFlA

# **Aula 4 - Estrutura de repetição - FOR**

## Atividade 1

#### Pseudocódigo

```
programa For_1

var
x: real
contador,r: inteiro

inicio

para contador de 1 ate 5 passo 1 faça:
  leia(x)
  r <- x*12
  escreva(r)
fim_para

fim

```
"""

for i in range(1,5):
  print(f'Essa é a posição {i}')
  x = float(input('Insira o valor de x: '))
  r = x*12
  print(r)

